// This file is auto-generated by scripts/genVersions.js. Do not edit.

export const PEBBLE_VERSION = "0.1.2";
export const PEBBLE_LIB_VERSION = "0.1.2";
export const PEBBLE_COMMIT_HASH = "40887038e5d00f171e4684f4c456ffd468008445";
