// This file is auto-generated by scripts/genVersions.js. Do not edit.

export const PEBBLE_VERSION = "0.1.1-dev0";
export const PEBBLE_LIB_VERSION = "0.1.1";
export const PEBBLE_COMMIT_HASH = "61b900fbd67de7283a60e45c9a98516fa4660d53";
