// Auto-generate version constants for the CLI.
// Reads the CLI package version and the local pebble package version.

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

async function main() {
	const cliRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
	const cliPkgPath = path.join(cliRoot, "package.json");
	const outPath = path.join(cliRoot, "src", "version.generated.ts");

	let cliVersion = "0.0.0";
	let pebbleVersion = "unknown";

	try {
		const cliPkg = JSON.parse(await readFile(cliPkgPath, "utf8"));
		cliVersion = cliPkg.version ?? cliVersion;

		// Try to read the local monorepo pebble package version first
		const pebblePkgPath = path.resolve(cliRoot, "..", "pebble", "package.json");
		if (existsSync(pebblePkgPath)) {
			const pebblePkg = JSON.parse(await readFile(pebblePkgPath, "utf8"));
			pebbleVersion = pebblePkg.version ?? pebbleVersion;
		} else if (cliPkg.dependencies && cliPkg.dependencies["@harmoniclabs/pebble"]) {
			// Fallback to whatever is declared in dependencies (may be a file: tgz path)
			pebbleVersion = String(cliPkg.dependencies["@harmoniclabs/pebble"]);
		}
	} catch (e) {
		console.error("Failed to read package versions:", e);
	}

	const banner = "// This file is auto-generated by scripts/genVersions.js. Do not edit.\n";
	const content = `${banner}
export const PEBBLE_VERSION = "${cliVersion}";
export const PEBBLE_LIB_VERSION = "${pebbleVersion}";
`;

	await writeFile(outPath, content, "utf8");
	console.log("Generated", path.relative(process.cwd(), outPath));
}

main();